ob:
  ssl:
    key-store: "/Users/qcastel/.ob/keystore.p12"
    check-hostname: false
  onboarding:
    default:
      request: "/Users/qcastel/.ob/onboarding.request.default.json"


server:
  ssl:
    enabled: true
    key-store: "/Users/qcastel/.ob/keystore.p12"
    key-store-password: changeit